In [18]:
import utils as ut
import pandas as pd
from utils import Config
import numpy as np

In [2]:
lat1 = [12,24]
lon1 = [10,15]
lat2 = [50,65]
lon2 = [75,20]

In [3]:
array = ut.haversine(lat1,lon1,lat2,lon2)

In [4]:
type(array)

numpy.ndarray

In [5]:
ut.bearing(lat1,lon1,lat2,lon2)

array([ 40.0588934 ,   3.21023191])

In [6]:
lat= [120,120]
lon =[5,5]
bearing =[5,85]
distance = 100000

In [7]:
ut.displace(lat,lon,bearing,distance)

(array([ 59.10500794,  59.90963556]), array([ 4.84752518,  3.2148538 ]))

In [8]:
mag = 8.5
dl1 = 1
ut.calc_length(mag,dl1)

3518137.82902592

In [9]:
mag = 3.2
length = 3.4
width = 2.1
ut.calc_slip(mag,length,width)

247.88017660509075

In [10]:
ut.Config.read('slab2_banda.npz')

TypeError: read() missing 1 required positional argument: 'file'

In [11]:
np.savez_compressed('slab2_banda.npz', array1=array1, array2=array2)
b = np.load('slab2_banda.npz')

NameError: name 'array1' is not defined

In [12]:
config = Config()

In [13]:
np.load(config.read('slab2_banda.npz'))

AttributeError: 'NoneType' object has no attribute 'read'

In [14]:
mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
          {'a': 100, 'b': 200, 'c': 300, 'd': 400},
          {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]
df = pd.DataFrame(mydict)
df

a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

In [15]:
df.iloc[0]

a    1
b    2
c    3
d    4
Name: 0, dtype: int64

In [17]:
df.iloc[-4:]

a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

In [18]:
df.loc[0]

a    1
b    2
c    3
d    4
Name: 0, dtype: int64

In [19]:
type(df.loc[0])

pandas.core.series.Series

In [20]:
import scenario

IndentationError: expected an indented block (scenario.py, line 27)

In [13]:
np.random.randn()

1.5512637225869446

In [25]:
samples = pd.DataFrame(columns=["Mag"])

In [26]:
samples.loc["Mag"] = 8.5

In [27]:
samples

Mag
Mag  8.5

In [22]:
samples["Mag"]

0    8.5
Name: Mag, dtype: float64

In [28]:
prop = .1*np.random.randn()+samples

In [29]:
prop

Mag
Mag  8.589271

In [30]:
import scipy.stats as stats

In [39]:

stats.halfnorm.rvs(size = 2)

array([ 0.27471073,  0.88372505])

In [38]:
stats.halfnorm.rvs()

0.41963490821740951

In [42]:
stats.halfnorm.logpdf([12.2,13.4])

array([-74.64579135, -90.00579135])

In [8]:
d = {'key' : 123}
d['dist_params'] = {}

In [9]:
d

{'dist_params': {}, 'key': 123}

In [12]:
d['dist_params']["key1"] = {'name': "Isaac",'shapes': "square"}
d['dist_params']["key2"] = {'name': "Grace",'shapes': "circle"}

In [13]:
d

{'dist_params': {'key1': {'name': 'Isaac', 'shapes': 'square'},
  'key2': {'name': 'Grace', 'shapes': 'circle'}},
 'key': 123}

In [14]:
from models import inundation

TypeError: unsupported operand type(s) for ** or pow(): 'method' and 'float'