In [1]:
from fault import BaseFault
from fault import GridFault
import numpy as np
import pandas as pd
from scipy.interpolate import RegularGridInterpolator
from scipy.stats import multivariate_normal

ImportError: attempted relative import with no known parent package

In [ ]:
bounds = [12.34,45.234,12.234,23.234]
lat,lon = [12.3,12.4], [13.45,14.6]
length = 200
width = 450
slip = 365
depth = [[1000,1200],[1250,1300]]
strike = [[265,245],[450,600]]
dip = [[120,125],[126,127]]

In [ ]:
basefault = BaseFault(bounds)
basefault

In [2]:
gridfault = GridFault(lat,lon,depth,dip,strike,bounds)




NameError: name 'GridFault' is not defined

In [254]:

gridfault.subfault_split(lat2,lon2,length,width,slip)

C:\Users\isaac\Documents\tsunamibayes\tsunamibayes\fault.py:74: RuntimeWarning: invalid value encountered in double_scalars
  bearing2 = (bearing1-180)%360


NameError: name 'displace' is not defined

In [196]:
dipmap = gridfault.dip_map(lat,lon)

In [197]:
print(dipmap)

[ 0.15  0.76]


In [198]:
depth_interp =  RegularGridInterpolator((lat,lon),depth,bounds_error=False)
print(depth_interp)

In [199]:
array =np.array([lat,lon]).T
array

array([[ 12.3 ,  13.45],
       [ 12.4 ,  14.6 ]])

In [200]:
array2 =depth_interp(array)
array2

array([ 1000.,  1300.])

In [201]:
2*array2

array([ 2000.,  2600.])

In [202]:
np.add(array, array2)

array([[ 1012.3 ,  1313.45],
       [ 1012.4 ,  1314.6 ]])

In [227]:

bearing2 = (bearing1-180)%360
bearing2

AttributeError: module 'numpy' has no attribute 'INF'